# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "ios/Ironbelly.xcodeproj")
    # increment_version_number(bump_type: "patch")
    build_app(workspace: "ios/Ironbelly.xcworkspace", scheme: "Ironbelly")
    upload_to_testflight()
  end
end

platform :android do
  desc "Submit a new Alpha Build to Play Market"
  lane :alpha do
    gradle(task: "clean bundleRelease", project_dir: 'android/')
    upload_to_play_store(track: 'alpha')
  end

  desc "Submit a new Internal Build to Play Market"
  lane :internal do
    gradle(task: "clean bundleRelease", project_dir: 'android/')
    upload_to_play_store(track: 'internal')
  end

  desc "Build Release APK"
  lane :apk do
    gradle(task: "clean assembleRelease", project_dir: 'android/')
  end
end

