# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Bump new version for iOS"

  lane :bumpVersion do |options|
    if options[:type]
      increment_version_number(xcodeproj: "ios/Ironbelly.xcodeproj", bump_type: options[:type])
    end
  end

  lane :bumpBuildNumber do |options|
      increment_build_number(xcodeproj: "ios/Ironbelly.xcodeproj")
  end

  desc "Push a new beta build to TestFlight"

  lane :beta do
    build_app(workspace: "ios/Ironbelly.xcworkspace", scheme: "Ironbelly", export_xcargs: "-allowProvisioningUpdates")
    upload_to_testflight()
  end
end

platform :android do
  desc "Submit a new Alpha Build to Play Market"
  lane :alpha do
    gradle(task: "clean bundleRelease", project_dir: 'android/')
    upload_to_play_store(track: 'alpha')
  end

  desc "Submit a new Internal Build to Play Market"
  lane :internal do
    gradle(task: "clean bundleRelease", project_dir: 'android/')
    upload_to_play_store(track: 'internal')
  end

  desc "Build Release APK"
  lane :apk do
    gradle(task: "clean assembleRelease", project_dir: 'android/')
  end

  lane :bumpVersion do |options|
    if options[:type]
      increment_version_name(
        gradle_file_path: "./android/app/build.gradle",
        bump_type: options[:type]
      )
    end
  end
  lane :bumpBuildNumber do |options|
    if options[:type]
      increment_version_code(gradle_file_path: "./android/app/build.gradle")
    end
  end
end

