# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Alpha Build to Play Market"
  lane :alpha do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(track: 'alpha')
  end

  desc "Submit a new Internal Build to Play Market"
  lane :internal do
    gradle(task: "clean assembleRelease")
    # Move back to bundleRelease once updated to RN 0.62+
    # https://github.com/facebook/react-native/issues/26400
    #
    # gradle(task: "clean bundleRelease")
    upload_to_play_store(track: 'internal')
  end

  desc "Build Release APK"
  lane :apk do
    gradle(task: "clean assembleRelease")
  end


end
